import React from 'react';
import { 
  Wallet, 
  TrendingUp, 
  BookOpen, 
  Award, 
  LayoutDashboard, 
  PlusCircle, 
  MinusCircle, 
  Brain,
  Target,
  Zap,
  DollarSign,
  Plus,
  Check,
  X,
  PiggyBank,
  User,
  Settings,
  Trash2,
  Edit2,
  Medal,
  RefreshCw,
  Sun,
  Moon,
  Camera,
  Upload,
  AlertTriangle
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Wallet: Wallet,
  Invest: TrendingUp,
  TrendingUp: TrendingUp,
  Learn: BookOpen,
  Trophy: Award,
  Income: PlusCircle,
  PlusCircle: PlusCircle,
  Expense: MinusCircle,
  MinusCircle: MinusCircle,
  AI: Brain,
  Target: Target,
  Zap: Zap,
  Dollar: DollarSign,
  Plus: Plus,
  Check: Check,
  X: X,
  PiggyBank: PiggyBank,
  User: User,
  Settings: Settings,
  Trash: Trash2,
  Edit: Edit2,
  Medal: Medal,
  Refresh: RefreshCw,
  Sun: Sun,
  Moon: Moon,
  Camera: Camera,
  Upload: Upload,
  Alert: AlertTriangle
};